import Head from 'next/head'
// import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai'

import Link from 'next/link';
import Image from 'next/image';
import skill1 from '../public/images/html.png'
import skill2 from '../public/images/css-3.png'
import skill3 from '../public/images/bootstrap.png'
import skill4 from '../public/images/js.png'
import skill5 from '../public/images/physics.png'
import skill6 from '../public/images/tailwind-css-icon.png'
// import skill7 from '../public/images/nextjs-icon.png'
import skill8 from '../public/images/mongodb-icon.png'
import skill9 from '../public/images/google-firebase-icon.png'
import pro1 from '../public/images/pro-1.png'
import pro2 from '../public/images/pro-2.png'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Kazi Marjan Sultana</title>
        <meta name="description" content="Generated by create next app" />

      </Head>

      <main className='bg-gradient-to-r from-black to-purple-900 md:px-20 lg:px-4' >
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons text-purple-600 '>MARJAN</h1>
            <ul className='flex items-center'>

              <li>
                <a className='bg-gradient-to-r from-purple-600 to-purple-500 text-white px-4 py-2 rounded-md ml-8' href="https://drive.google.com/file/d/1ccKTyE2UpjdlwVq8yN1DaLs8KQCTEBdR/view?usp=share_link">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className='text-5xl py-2 text-purple-600 font-medium '>Kazi Marjan Sultana</h2>
            <h3 className='text-2xl py-2 text-purple-600 '>Hi! I am Front-End Developer</h3>
            <p className='text-md py-5 leading-8 text-white max-w-xl mx-auto'>A curious front-end developer who always ready to explore new technologies. Passionate about what I am doing. Always ready to face challenge.</p>
          </div>
          <div className='text-5xl flex justify-center gap-10  text-purple-600'>
            <Link href="https://www.linkedin.com/in/kazi-marjan-sultana-8b5529250"> <AiFillLinkedin></AiFillLinkedin></Link>
            <Link href="https://github.com/Marjan-001"><AiFillGithub></AiFillGithub> </Link>


          </div>
        </section>
        {/* 2nd Part */}
        <section>
          <h3 className='text-3xl py-1 text-center text-purple-600'> About Me</h3>
          <p data-aos="zoom-in" className='text-lg leading-8 text-center  text-white max-w-xl mx-auto'>Hello, I am Marjan. I have completed my graduation in Computer Science and Engineering.I am a front-end Developer.I design and develop websites and web applications using HTML, CSS, JavaScript, React Js, Next Js,Tailwind, Bootstrap, MongoDb, Express Js, Material UI. When dealing with a project I pay attention to the smallest details addressing problems with patience. Web design and development help me to free my creative mind and allow me satisfy my desire towards constant self growth.  </p>

        </section>
        <section>
          <h3 className='text-3xl py-10 text-center text-purple-600'> My Skills</h3>

          <div className='grid  grid-cols-2 lg:grid-cols-3 justify-items-center gap-4'>
            <Image data-aos="fade-up" src={skill1} width={100} height={100} alt='' />
            <Image data-aos="fade-up" src={skill2} width={100} height={100} alt='' />
            <Image data-aos="fade-up" src={skill3} width={100} height={100} alt='' />
            <Image data-aos="fade-up" src={skill4} width={100} height={100} alt='' />
            <Image data-aos="fade-up" src={skill5} width={100} height={100} alt='' />
            <Image data-aos="fade-up" src={skill6} width={100} height={100} alt='' />
            {/* <Image src={skill7} width={100} height={100} alt='' /> */}
            <Image data-aos="fade-up" src={skill8} width={80} height={80} alt='' />
            <Image data-aos="fade-up" src={skill9} width={100} height={100} alt='' />
          </div>
        </section>
        <section>
          <h3 className='text-3xl py-10 text-center text-purple-600'> My Projects</h3>
          <div className='grid  grid-cols-1  justify-items-center gap-4' >
            <Image src={pro1} width={900} height={700} alt='' />
            <a className='bg-gradient-to-r from-purple-600 to-purple-500 text-white px-4 py-2 rounded-md ml-8' href="https://assignment-11-personal-stylist.web.app/">Live Site</a>
            <Image className="py=10" src={pro2} width={900} height={700} alt='' />
            <a className='bg-gradient-to-r from-purple-600 to-purple-500 text-white px-4 py-2 rounded-md ml-8' href="https://laptop-swappers.web.app/">Live Site</a>
          </div>
        </section>
        <footer className="bg-gradient-to-r from-black to-purple-900 text-white">
          <div className="container flex flex-col p-4 mx-auto md:p-8 lg:flex-row divide-gray-400">
            <ul className="self-center py-6 space-y-4 text-center sm:flex sm:space-y-0 sm:justify-around sm:space-x-4 lg:flex-1 lg:justify-start">
              <li>Kazi Marjan Sultana |</li>
              <li>Contact: +8801799399716 |</li>
              <li>Email:marjansultana229@gmail.comss </li>

            </ul>
            <div className="flex flex-col justify-center pt-6 lg:pt-0">
              <div className="flex justify-center space-x-4">
                <Link href="https://www.linkedin.com/in/kazi-marjan-sultana-8b5529250" > <AiFillLinkedin></AiFillLinkedin></Link>
                <Link href="https://github.com/Marjan-001"><AiFillGithub></AiFillGithub> </Link>




              </div>
            </div>
          </div>
        </footer>
      </main>


    </div>
  )
}
